# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  lanches:
    image: lanches
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5036:5036
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
   